apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-nodejs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fasih6/three-tier-nodejs-gitops.git
    targetRevision: main
    path: .                      # since Chart.yaml is at root
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true                # delete resources removed from git
      selfHeal: true             # revert manual kubectl changes
